export interface MinecraftTourCapabilities { settings: boolean; manageProfiles: boolean; power: boolean }
export interface MinecraftTourStep {
  id: string; route: string | "profile-detail"; selector?: string; title: string; description: string;
  unavailable: string; capability?: keyof MinecraftTourCapabilities; immediateFallback?: boolean;
}
export function minecraftTourSelector(name: string): string { return `[data-minecraft-tour="${name}"]`; }
export function minecraftTourHeading(path: string): string {
  return minecraftTourSelector(path === "/minecraft/mods" ? "mods" : path === "/minecraft/backups" ? "backups" : path === "/minecraft/server" ? "server" : path === "/minecraft/settings" ? "settings" : path.startsWith("/minecraft/profiles/") ? "profile-image" : "profiles");
}
export function minecraftTourProfileHref(value: string | null): string | null {
  return value && /^\/minecraft\/profiles\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(value) ? value : null;
}
/** Descriptions are owned static text. A tour never submits a game action. */
export function minecraftTourSteps(path: string, capabilities: MinecraftTourCapabilities): MinecraftTourStep[] {
  const step = (id: string, route: string, target: string, title: string, description: string, unavailable: string, capability?: keyof MinecraftTourCapabilities): MinecraftTourStep => ({ id, route, selector: minecraftTourSelector(target), title, description, unavailable, capability });
  return [
    { id: "welcome", route: path, selector: minecraftTourHeading(path), title: "A quick tour of Minecraft", description: "We’ll point out the real screens for your worlds, joining and looking after a server. Nothing is started, changed or restored by this tour. Use Next to look around, or Skip tour to remember that you’ve seen it.", unavailable: "This screen’s heading is not available. The tour can still explain the other Minecraft screens." },
    step("worlds", "/minecraft", "worlds", "Your worlds, kept together", "A profile keeps a world with its Minecraft version, loader, mods and settings. These cards let you return to the right save when you play with different friends.", "The world list is not available right now. It may still be loading, or its read may have failed. A profile keeps each world with its own version and mods."),
    step("create", "/minecraft", "profile-create", "Prepare another adventure", "Create profile prepares a separate world. You can choose vanilla, a loader or an exact modpack build. Review the real dialog when you use it; this tour leaves the button alone.", "Create profile is not available on this screen. It needs current management permission and verified profile data.", "manageProfiles"),
    step("current", "/minecraft", "current-profile", "Know which world is applied", "The current-profile panel identifies the selected world and its observed server state. Managers choose a profile before starting; changing a running profile saves and stops the current Minecraft world, with peer-server confirmation when needed.", "No current-profile panel is available. An existing server may need adoption, or no prepared profile may be selected yet."),
    { ...step("cover", "profile-detail", "profile-image", "Give each world a face", "Profile details show the saved-world overview and its source time. A manual upload or player screenshot takes priority. Generated images use saved chunks and can simplify modded blocks; they are not live player-camera captures.", "There is no readable profile detail link to open, or its image section is unavailable. Create or open a profile later to inspect its cover."), route: "profile-detail" },
    step("join", "/minecraft", "join", "Join with the right client", "How to join shows the server address and the exact target when it can be verified. Match the version, loader and client modpack. Copying an address does not start the server or prove that a client joined.", "The join panel is unavailable here. The Minecraft address is mc.yoshling.xyz; check the real join panel for the profile’s verified client target."),
    step("mods", "/minecraft/mods", "mods-installed", "See what this world uses", "Installed mods belong to the applied Minecraft profile. Search and filters help you inspect them. Managers can change mods only through the actual reviewed controls; this tour installs or removes nothing.", "The installed-mod list could not be highlighted. Check its read state on the Mods screen before making changes."),
    step("sets", "/minecraft/mods", "saved-mod-sets", "Keep reusable mod sets", "Saved mod sets are reusable collections, separate from a profile’s world save. Review versions and the resulting operation before applying a set to a profile.", "Saved mod sets are not available on this screen right now. Their absence is not proof that no sets exist."),
    step("backups", "/minecraft/backups", "backup-list", "Keep a way back", "Backups belong to the selected profile. Members can inspect the records; managers can create, download or restore through the real controls. Check the saved source, checksum and operation result before trusting a backup or restore.", "The backup list could not be highlighted. Check the screen’s read state; this tour cannot establish that a backup exists or can be restored."),
    step("server", "/minecraft/server", "server-tabs", "Inspect the server", "The Server screen contains logs and the tools your role may use. Logs can help with a failed boot. Console commands and file edits are real actions, so use their permissions and current profile identity carefully.", "The server tools could not be highlighted. Available tabs depend on your current access and the screen’s read state."),
    step("settings", "/minecraft/settings", "settings", "Review settings in context", "Settings distinguish configured values from values verified in the running game. Profile target and world settings are kept with the profile; global memory and control settings affect the shared server. Review any real save or restart separately.", "Settings require confirmed current access. The tour will not open them while that capability is unknown or revoked.", "settings"),
    { ...step("results", "/minecraft", "operation-strip", "Follow the result", "Long actions report steps and verified outcomes in the operation bar. Queued, refused, partial and unconfirmed results are different from success. Finish remembers this tour for your account; Take tour replays it any time.", "There is no visible operation bar right now. It appears when there is work to follow. Queued, refused, partial and unconfirmed results are different from success."), immediateFallback: true },
  ].filter(item => !item.capability || capabilities[item.capability]);
}
