import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  //
  // **`npm run lint` reported 349,969 problems (31,743 errors) until 2026-10-06**, against
  // **59 (45 errors)** for the project's own source — so the one command whose job is to
  // report problems was unusable, while CLAUDE.md described it as clean apart from a few
  // `any` warnings.
  //
  // The cause was NOT the generated Prisma client, which was the first guess: it is that
  // `.next/**` matches only the *top-level* build output, and `.claude/worktrees/*/` — the
  // scratch checkouts background agents work in — each contain their own `.next`, built and
  // then abandoned. Eight of them contributed ~7,000 problems apiece. Measured by running
  // `eslint -f json` and grouping by directory, after the Prisma guess turned out to change
  // nothing.
  //
  // Both are ignored now, and both are gitignored and not ours to fix: `src/generated` is
  // regenerated by `prisma generate`, and `.claude/worktrees` is agent scratch space.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated, gitignored, not ours:
    "src/generated/**",
    // Agent scratch worktrees, each with its own abandoned `.next`. The default `.next/**`
    // does not reach a nested one.
    ".claude/**",
    "**/.next/**",
  ]),
]);

export default eslintConfig;
