// @vitest-environment jsdom
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MinecraftProfiles } from "@/components/minecraft-profiles";
import { MinecraftProfilePicker } from "@/components/minecraft-profile-picker";
import { MinecraftProfileCreate } from "@/components/minecraft-profile-create";
import { MinecraftProfileDetail } from "@/components/minecraft-profile-detail";
import { GameControls } from "@/components/game-controls";
import { GameOverview } from "@/components/game-overview";
import { MissionControl } from "@/components/mission-control";
import { gamesState, installBrowserStubs, NO_POWERS, opsState, op, worlds } from "./helpers/dom";
import { profileFixture, profilesFixture, secondProfile, worldSettingsFixture } from "./helpers/minecraft-profiles";
import { waitingOverview } from "./helpers/minecraft-overviews";
const boundary = vi.hoisted(() => ({ games: null as unknown, operations: null as unknown }));
vi.mock("@/lib/use-games", async original => ({ ...(await original<typeof import("@/lib/use-games")>()), useGames: () => boundary.games }));
vi.mock("@/components/operations-provider", () => ({ useOperations: () => boundary.operations }));
const toasts = vi.hoisted(() => ({ success: vi.fn(), error: vi.fn(), info: vi.fn() }));
vi.mock("sonner", () => ({ toast: toasts }));
beforeAll(installBrowserStubs);
beforeEach(() => { boundary.games = gamesState({ lastSuccessAt: Date.now() }); boundary.operations = opsState(); vi.clearAllMocks(); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.useRealTimers(); });
const json = (value: unknown, status = 200, revision = '"file-r1"') => new Response(JSON.stringify(value), { status, headers: { "X-File-Revision": revision } });
function requests(list = profilesFixture(), write = json({ operationId: "op-profile", profile: secondProfile })) {
  const calls: { url: string; method: string; body: unknown; headers: Headers }[] = [];
  vi.stubGlobal("fetch", vi.fn(async (input, init) => { const url = String(input), method = init?.method ?? "GET"; calls.push({ url, method, body: init?.body instanceof FormData ? init.body : init?.body ? JSON.parse(init.body) : null, headers: new Headers(init?.headers) });
    if (method !== "GET") return write;
    if (url === "/api/minecraft/profiles") return json(list);
    if (url.endsWith("/overview")) return json({ profileId: decodeURIComponent(url.split("/").at(-2)!), overview: waitingOverview() });
    if (url.endsWith("/world-settings")) return json(worldSettingsFixture());
    if (url.endsWith("/p2")) return json({ profile: secondProfile, runtime: list.runtime, capabilities: list.capabilities });
    if (url === "/api/minecraft-versions") return json({ versions: ["1.21.1", "26.1.2"] });
    if (url === "/api/modpacks") return json([{ id: "set", name: "Saved Fabric Set", targetMcVersion: "1.21.1", targetLoader: "fabric" }]);
    if (url.startsWith("/api/modpacks/search")) return json({ hits: [{ project_id: "published", title: "Published Pack" }] });
    if (url.startsWith("/api/minecraft/profile-sources/modrinth")) return json({ project: { id: "published", title: "Published Pack" }, versions: [{ id: "exact-build", name: "Adventure release", versionNumber: "4.2", mcVersions: ["1.21.1"], loaders: ["fabric"], publishedAt: "2026-10-07T10:00:00Z", supported: true }] });
    return json({});
  })); return calls;
}
describe("profile gallery and preparation", () => {
  it("shows named screenshot cards, exact targets, source titles and honest last-played state", async () => { const calls = requests(); render(<MinecraftProfiles />); await screen.findByRole("article", { name: "Profile Adventure Pack" }); const card = within(screen.getByRole("article", { name: "Profile Adventure Pack" })); expect(card.getByText("Created from Adventure Published Pack · 34 mods")).toBeTruthy(); expect(card.getByText("Last played: Not recorded")).toBeTruthy(); expect(card.getByText("World illustration")).toBeTruthy(); expect(card.getByText("Minecraft 1.21.1 · fabric")).toBeTruthy(); expect(calls.every(call => call.method === "GET")).toBe(true); });
  it.each([503, 200])("refuses failed/incomplete initial collection HTTP%s and supports retry", async status => { let reads = 0; vi.stubGlobal("fetch", vi.fn(async () => ++reads === 1 ? json({ profiles: [] }, status) : json(profilesFixture()))); render(<MinecraftProfiles />); await screen.findByRole("alert"); expect(screen.queryByRole("button", { name: "Create profile" })).toBeNull(); fireEvent.click(screen.getByRole("button", { name: "Retry Minecraft profiles" })); await screen.findByRole("article", { name: "Profile Cozy Survival" }); });
  it("allows members to read cards without enabling create or play", async () => { boundary.games = gamesState({ can: NO_POWERS }); requests(profilesFixture({ capabilities: { read: true, manage: false, start: false, switch: false } })); render(<MinecraftProfiles />); await screen.findByRole("article", { name: "Profile Cozy Survival" }); expect(screen.queryByRole("button", { name: "Create profile" })).toBeNull(); expect(screen.getAllByRole("button", { name: "Start this profile" }).every(button => (button as HTMLButtonElement).disabled)).toBe(true); });
  it("prepares vanilla separately from start with an exact seed string and automatic Java", async () => { const onPrepared = vi.fn(); const calls = requests(); render(<MinecraftProfileCreate open data={profilesFixture()} onPrepared={onPrepared} onOpenChange={vi.fn()} />); await waitFor(() => expect(screen.getByRole("option", { name: "1.21.1" })).toBeTruthy()); fireEvent.change(screen.getByRole("textbox", { name: "Profile name" }), { target: { value: "Fresh world" } }); fireEvent.change(screen.getByRole("combobox", { name: "Minecraft version" }), { target: { value: "1.21.1" } }); fireEvent.change(screen.getByRole("textbox", { name: "New world seed (optional)" }), { target: { value: "-1234567890123456789" } }); fireEvent.click(screen.getByRole("button", { name: "Prepare profile" })); await waitFor(() => expect(onPrepared).toHaveBeenCalled()); expect(calls.filter(call => call.method === "POST")).toMatchObject([{ url: "/api/minecraft/profiles", body: { source: { kind: "vanilla", mcVersion: "1.21.1", loader: "vanilla" }, settings: { "level-seed": "-1234567890123456789" } } }]); expect(calls.some(call => call.url.includes("/start") || call.url === "/api/games/control")).toBe(false); });
  it("discovers Modrinth packs across versions and never imports/applies during selection", async () => { const calls = requests(); render(<MinecraftProfileCreate open data={profilesFixture()} onPrepared={vi.fn()} onOpenChange={vi.fn()} />); fireEvent.click(screen.getByRole("button", { name: "Published pack" })); await screen.findByRole("option", { name: "Published Pack" }); fireEvent.change(screen.getByRole("combobox", { name: "Published pack" }), { target: { value: "published" } }); expect(calls.find(call => call.url.startsWith("/api/modpacks/search"))?.url).toContain("version=any&loader=any"); expect(calls.every(call => call.method === "GET")).toBe(true); });
  it("requires explicit running-world adoption disconnection confirmation and never starts a game", async () => { boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true } }), lastSuccessAt: Date.now() }); const calls = requests(); render(<MinecraftProfileCreate open adopt data={profilesFixture({ requiresAdoption: true })} onPrepared={vi.fn()} onOpenChange={vi.fn()} />); fireEvent.change(screen.getByRole("textbox", { name: "Profile name" }), { target: { value: "Keep our world" } }); expect((screen.getByRole("button", { name: "Keep existing world" }) as HTMLButtonElement).disabled).toBe(true); fireEvent.click(screen.getByRole("checkbox")); fireEvent.click(screen.getByRole("button", { name: "Keep existing world" })); await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(calls.filter(call => call.method === "POST")).toMatchObject([{ url: "/api/minecraft/profiles/adopt", body: { name: "Keep our world", confirmStopCurrent: true } }]); });
});
describe("profile selection admission", () => {
  it.each([() => <GameControls game="minecraft" />, () => <GameOverview game="minecraft" />, () => <MissionControl access={["minecraft"]} />])("opens a picker from each stopped power surface without raw start", async surface => { const calls = requests(); render(surface()); fireEvent.click(screen.getByRole("button", { name: /Power on/ })); await screen.findByRole("dialog", { name: "Choose a Minecraft profile to start" }); expect(calls.some(call => call.method === "POST")).toBe(false); fireEvent.click(screen.getByRole("button", { name: /Adventure Pack.*Ready/ })); fireEvent.click(screen.getByRole("button", { name: "Start selected profile" })); await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(calls.find(call => call.method === "POST")).toMatchObject({ url: "/api/minecraft/profiles/p2/start", body: { expectedRevision: "context-r1", confirmStopPeers: false } }); expect(calls.some(call => call.url === "/api/games/control")).toBe(false); });
  it("requires confirmation that names real running peers and Minecraft player disconnections", async () => { boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true, players: { online: 3, max: 10, players: [] } }, zomboid: { status: "online", containerRunning: true } }), lastSuccessAt: Date.now() }); const calls = requests(); render(<MinecraftProfilePicker open initialProfileId="p2" onOpenChange={vi.fn()} />); await screen.findByText(/Selected:/); expect(screen.getByText(/with 3 connected players/)).toBeTruthy(); expect(screen.getByText(/Project Zomboid is running and will be saved and stopped/)).toBeTruthy(); expect((screen.getByRole("button", { name: "Switch & restart" }) as HTMLButtonElement).disabled).toBe(true); fireEvent.click(screen.getByRole("checkbox")); fireEvent.click(screen.getByRole("button", { name: "Switch & restart" })); await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(toasts.success).not.toHaveBeenCalled(); });
  it.each([{ lastSuccessAt: null }, { lastSuccessAt: Date.now() - 30000 }, { pollError: "Read failed" }, { can: NO_POWERS }])("gates an initial profile action on current permissions/status %j", async state => { boundary.games = gamesState(state); const calls = requests(); render(<MinecraftProfilePicker open initialProfileId="p2" onOpenChange={vi.fn()} />); await screen.findByText(/Selected:/); const start = screen.getByRole("button", { name: "Start selected profile" }) as HTMLButtonElement; expect(start.disabled).toBe(true); fireEvent.click(start); expect(calls.every(call => call.method === "GET")).toBe(true); });
  it("keeps a lost proxy receipt unconfirmed, refreshes the ledger and blocks automatic retry", async () => { const refresh = vi.fn(async () => {}); boundary.operations = opsState({ refresh }); const calls = requests(profilesFixture(), new Response("gateway", { status: 524 })); render(<MinecraftProfilePicker open initialProfileId="p2" onOpenChange={vi.fn()} />); await screen.findByText(/Selected:/); fireEvent.click(screen.getByRole("button", { name: "Start selected profile" })); await screen.findByRole("alert"); expect(screen.getByRole("alert").textContent).toContain("result is unconfirmed"); expect(refresh).toHaveBeenCalled(); expect((screen.getByRole("button", { name: "Start selected profile" }) as HTMLButtonElement).disabled).toBe(true); expect(calls.filter(call => call.method === "POST")).toHaveLength(1); expect(toasts.success).not.toHaveBeenCalled(); });
});
describe("inactive profile editing", () => {
  it("keeps generated-world seed read-only and saves only an inactive difficulty with its revision", async () => { const calls: { body: unknown; headers: Headers }[] = []; let difficulty = "normal"; vi.stubGlobal("fetch", vi.fn(async (url, init) => { if (init?.method === "PUT") { calls.push({ body: JSON.parse(init.body), headers: new Headers(init.headers) }); difficulty = "hard"; return json({ profileId: "p2", applied: ["difficulty"], ignored: [], properties: { difficulty, "level-seed": "1234567890123456789" } }, 200, '"file-r2"'); } if (String(url).endsWith("world-settings")) return json(worldSettingsFixture({ worldGenerated: true, properties: { difficulty, "level-seed": "1234567890123456789" } }), 200, difficulty === "hard" ? '"file-r2"' : '"file-r1"'); return json({ profile: secondProfile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }); })); render(<MinecraftProfileDetail id="p2" />); await screen.findByRole("textbox", { name: "difficulty" }); expect((screen.getByRole("textbox", { name: "level-seed" }) as HTMLInputElement).disabled).toBe(true); fireEvent.change(screen.getByRole("textbox", { name: "difficulty" }), { target: { value: "hard" } }); fireEvent.click(screen.getByRole("button", { name: "Save world settings" })); await screen.findByText(/World settings file values read back and saved/); expect(calls[0].body).toEqual({ updates: { difficulty: "hard" } }); expect(calls[0].headers.get("X-Expected-File-Revision")).toBe('"file-r1"'); });
  it("refuses active-profile world edits while preserving profile metadata", async () => { requests(profilesFixture({ runtime: { ...profilesFixture().runtime, selectedProfileId: "p2", appliedProfileId: "p2" } })); render(<MinecraftProfileDetail id="p2" />); await screen.findByRole("textbox", { name: "difficulty" }); expect((screen.getByRole("textbox", { name: "difficulty" }) as HTMLInputElement).disabled).toBe(true); expect((screen.getByRole("button", { name: "Save world settings" }) as HTMLButtonElement).disabled).toBe(true); expect((screen.getByRole("textbox", { name: "Name" }) as HTMLInputElement).disabled).toBe(false); });
  it("drops a delayed detail response when navigating to another profile ID", async () => { let resolve!: (value: Response) => void; const slow = new Promise<Response>(ok => { resolve = ok; }); vi.stubGlobal("fetch", vi.fn(async url => String(url).endsWith("/p1") ? slow : String(url).endsWith("world-settings") ? json(worldSettingsFixture()) : json({ profile: secondProfile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }))); const view = render(<MinecraftProfileDetail id="p1" />); view.rerender(<MinecraftProfileDetail id="p2" />); await screen.findByRole("heading", { name: "Adventure Pack", level: 1 }); await act(async () => resolve(json({ profile: profileFixture(), runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }))); expect(screen.queryByRole("heading", { name: "Cozy Survival", level: 1 })).toBeNull(); });
});

describe("profile workflow receipts and revisions", () => {
  it("does not block profile start on an inactive unrelated game's backup", async () => { boundary.operations = opsState({ operations: [op({ game: "zomboid", resources: ["files:zomboid"] })] }); requests(); render(<MinecraftProfilePicker open initialProfileId="p2" onOpenChange={vi.fn()} />); await screen.findByText(/Selected:/); expect(screen.queryByText(/Wait for Project Zomboid/)).toBeNull(); expect((screen.getByRole("button", { name: "Start selected profile" }) as HTMLButtonElement).disabled).toBe(false); });
  it("offers current-profile recovery separately from an already-running picker no-op", async () => { boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true } }) }); requests(profilesFixture({ runtime: { ...profilesFixture().runtime, state: "running" } })); render(<MinecraftProfilePicker open initialProfileId="p1" onOpenChange={vi.fn()} />); await screen.findByText(/This profile is already running/); fireEvent.click(screen.getByRole("checkbox")); expect((screen.getByRole("button", { name: "Switch & restart" }) as HTMLButtonElement).disabled).toBe(true); });
  it("does not mark deletion complete while collection readback still contains the profile", async () => { const calls = requests(profilesFixture(), json({ deleted: true, id: "p2", operationId: "delete-op" })); render(<MinecraftProfileDetail id="p2" />); await screen.findByText("Advanced: permanently delete this profile"); fireEvent.click(screen.getByText("Advanced: permanently delete this profile")); fireEvent.click(screen.getByRole("button", { name: "Delete profile" })); fireEvent.change(screen.getByRole("textbox", { name: "Profile name confirmation" }), { target: { value: "Adventure Pack" } }); fireEvent.click(screen.getByRole("button", { name: "Delete this profile permanently" })); await screen.findByText(/profile deletion result is unconfirmed/); expect(screen.queryByRole("heading", { name: "Profile removed from the list" })).toBeNull(); expect(calls.filter(call => call.method === "DELETE")).toHaveLength(1); });
  it("refuses a cover receipt naming another profile and preserves the selected screenshot", async () => { const calls = requests(profilesFixture(), json({ profile: profileFixture({ revision: 2, coverUrl: "/api/minecraft/profiles/p1/cover?v=2" }) })); render(<MinecraftProfileDetail id="p2" />); const input = await screen.findByLabelText("JPEG, PNG or WebP cover"); fireEvent.change(input, { target: { files: [new File(["fixture"], "world.png", { type: "image/png" })] } }); fireEvent.click(screen.getByRole("button", { name: "Upload cover" })); await screen.findByText(/cover receipt is unconfirmed/); expect(screen.queryByText("Cover upload read back.")).toBeNull(); expect(calls.filter(call => call.method === "POST")).toHaveLength(1); expect((screen.getByRole("button", { name: "Upload cover" }) as HTMLButtonElement).disabled).toBe(true); });
  it("keeps preparation disabled after a failed pack-build read and retries without guessing a pin", async () => { const calls = requests(); const base = globalThis.fetch; let reads = 0; vi.stubGlobal("fetch", vi.fn(async (url, init) => String(url).includes("profile-sources") && ++reads === 1 ? json({ error: "Pack builds unavailable" }, 503) : base(url, init))); render(<MinecraftProfileCreate open data={profilesFixture()} onPrepared={vi.fn()} onOpenChange={vi.fn()} />); fireEvent.change(screen.getByRole("textbox", { name: "Profile name" }), { target: { value: "New pack" } }); fireEvent.click(screen.getByRole("button", { name: "Published pack" })); await screen.findByRole("option", { name: "Published Pack" }); fireEvent.change(screen.getByRole("combobox", { name: "Published pack" }), { target: { value: "published" } }); await screen.findByText("Pack builds unavailable"); expect((screen.getByRole("button", { name: "Prepare profile" }) as HTMLButtonElement).disabled).toBe(true); expect(calls.every(call => call.method === "GET")).toBe(true); fireEvent.click(screen.getByRole("button", { name: "Recheck pack builds" })); await screen.findByRole("option", { name: /Adventure release/ }); expect((screen.getByRole("button", { name: "Prepare profile" }) as HTMLButtonElement).disabled).toBe(true); });
  it("ignores a delayed version list belonging to a previously selected pack", async () => {
    const calls = requests(); const base = globalThis.fetch; let resolve!: (value: Response) => void; const old = new Promise<Response>(ok => { resolve = ok; });
    const response = (id: string) => json({ project: { id, title: id }, versions: [{ id: `${id}-build`, name: `${id} exact build`, versionNumber: "2", mcVersions: ["1.21.1"], loaders: ["fabric"], publishedAt: "2026-10-07T10:00:00Z", supported: true }] });
    vi.stubGlobal("fetch", vi.fn(async (url, init) => String(url).includes("/modpacks/search") ? json({ hits: [{ project_id: "A", title: "Pack A" }, { project_id: "B", title: "Pack B" }] }) : String(url).includes("profile-sources") ? String(url).endsWith("ref=A") ? old : response("B") : base(url, init)));
    render(<MinecraftProfileCreate open data={profilesFixture()} onPrepared={vi.fn()} onOpenChange={vi.fn()} />); fireEvent.click(screen.getByRole("button", { name: "Published pack" })); await screen.findByRole("option", { name: "Pack A" }); fireEvent.change(screen.getByRole("combobox", { name: "Published pack" }), { target: { value: "A" } }); fireEvent.change(screen.getByRole("combobox", { name: "Published pack" }), { target: { value: "B" } }); await screen.findByRole("option", { name: /B exact build/ }); await act(async () => resolve(response("A"))); expect(screen.queryByRole("option", { name: /A exact build/ })).toBeNull(); expect(screen.getByRole("option", { name: /B exact build/ })).toBeTruthy(); expect(calls.every(call => call.method === "GET")).toBe(true);
  });
  it("does not enable a settings write when its opaque file revision is missing", async () => { vi.stubGlobal("fetch", vi.fn(async url => String(url).endsWith("world-settings") ? new Response(JSON.stringify(worldSettingsFixture())) : json({ profile: secondProfile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }))); render(<MinecraftProfileDetail id="p2" />); const difficulty = await screen.findByRole("textbox", { name: "difficulty" }); fireEvent.change(difficulty, { target: { value: "hard" } }); expect((screen.getByRole("button", { name: "Save world settings" }) as HTMLButtonElement).disabled).toBe(true); });
  it("ignores an older same-profile settings read after a newer explicit reload completed", async () => {
    let resolve!: (value: Response) => void; const old = new Promise<Response>(ok => { resolve = ok; }); let reads = 0;
    vi.stubGlobal("fetch", vi.fn(async url => { if (!String(url).endsWith("world-settings")) return json({ profile: secondProfile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }); if (++reads === 1) return json({ error: "Temporary read failure" }, 503); if (reads === 2) return old; return json(worldSettingsFixture({ properties: { difficulty: "hard", "level-seed": "1234567890123456789" } }), 200, '"newer-r3"'); }));
    render(<MinecraftProfileDetail id="p2" />); await screen.findByRole("button", { name: "Reload world settings" }); act(() => { fireEvent.click(screen.getByRole("button", { name: "Reload world settings" })); fireEvent.click(screen.getByRole("button", { name: "Reload world settings" })); }); await screen.findByDisplayValue("hard"); await act(async () => resolve(json(worldSettingsFixture(), 200, '"older-r2"'))); expect((screen.getByRole("textbox", { name: "difficulty" }) as HTMLInputElement).value).toBe("hard");
  });
  it("does not clear metadata from a readback that disagrees with its accepted value receipt", async () => {
    let written = false; vi.stubGlobal("fetch", vi.fn(async (url, init) => { if (init?.method === "PATCH") { written = true; return json({ profile: { ...secondProfile, name: "My requested name", revision: 2 } }); } if (String(url).endsWith("overview")) return json({ profileId: "p2", overview: waitingOverview() }); if (String(url).endsWith("world-settings")) return json(worldSettingsFixture()); return json({ profile: { ...secondProfile, revision: written ? 2 : 1 }, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }); })); render(<MinecraftProfileDetail id="p2" />); fireEvent.change(await screen.findByRole("textbox", { name: "Name" }), { target: { value: "My requested name" } }); fireEvent.click(screen.getByRole("button", { name: "Save profile details" })); await waitFor(() => expect(screen.queryByText("Profile details read back and saved.") || screen.queryByRole("alert")).not.toBeNull()); expect(screen.queryByText("Profile details read back and saved.")).toBeNull(); expect((screen.getByRole("textbox", { name: "Name" }) as HTMLInputElement).value).toBe("My requested name");
  });
  it("selects a named exact published build before preparation rather than guessing latest", async () => {
    const calls = requests(); render(<MinecraftProfileCreate open data={profilesFixture()} onPrepared={vi.fn()} onOpenChange={vi.fn()} />);
    fireEvent.change(screen.getByRole("textbox", { name: "Profile name" }), { target: { value: "Pack world" } }); fireEvent.click(screen.getByRole("button", { name: "Published pack" }));
    await screen.findByRole("option", { name: "Published Pack" }); fireEvent.change(screen.getByRole("combobox", { name: "Published pack" }), { target: { value: "published" } });
    await screen.findByRole("option", { name: /Adventure release.*4.2.*1.21.1.*fabric/ }); expect((screen.getByRole("button", { name: "Prepare profile" }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(screen.getByRole("combobox", { name: "Published pack build" }), { target: { value: "exact-build" } }); fireEvent.click(screen.getByRole("button", { name: "Prepare profile" }));
    await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(calls.find(call => call.method === "POST")?.body).toMatchObject({ source: { kind: "modrinth", ref: "published", versionId: "exact-build" } });
  });
  it("prepares a custom Fabric target with automatic pinned loader resolution while NeoForge needs a build", async () => {
    const calls = requests(); render(<MinecraftProfileCreate open data={profilesFixture()} onPrepared={vi.fn()} onOpenChange={vi.fn()} />); await screen.findByRole("option", { name: "1.21.1" });
    fireEvent.change(screen.getByRole("textbox", { name: "Profile name" }), { target: { value: "Custom world" } }); fireEvent.change(screen.getByRole("combobox", { name: "Minecraft version" }), { target: { value: "1.21.1" } });
    fireEvent.change(screen.getByRole("combobox", { name: "Loader" }), { target: { value: "neoforge" } }); expect((screen.getByRole("button", { name: "Prepare profile" }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(screen.getByRole("combobox", { name: "Loader" }), { target: { value: "fabric" } }); expect((screen.getByRole("button", { name: "Prepare profile" }) as HTMLButtonElement).disabled).toBe(false); fireEvent.click(screen.getByRole("button", { name: "Prepare profile" }));
    await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(calls.find(call => call.method === "POST")?.body).toMatchObject({ source: { kind: "vanilla", mcVersion: "1.21.1", loader: "fabric" } }); expect(calls.find(call => call.method === "POST")?.body).not.toHaveProperty("javaVariant");
  });
  it("sends reviewed adoption hints with no invented peer-stop or start confirmation", async () => {
    const calls = requests(); render(<MinecraftProfileCreate open adopt data={profilesFixture({ requiresAdoption: true })} onPrepared={vi.fn()} onOpenChange={vi.fn()} />);
    fireEvent.click(screen.getByText("Advanced: resolve an ambiguous existing installation")); fireEvent.change(screen.getByRole("textbox", { name: "Profile name" }), { target: { value: "Existing Forge" } }); fireEvent.change(screen.getByRole("textbox", { name: "Reviewed existing loader build (optional)" }), { target: { value: "47.2.0" } }); fireEvent.change(screen.getByRole("combobox", { name: "Reviewed existing Java runtime (optional)" }), { target: { value: "java17" } }); fireEvent.click(screen.getByRole("button", { name: "Keep existing world" }));
    await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(calls.find(call => call.method === "POST")?.body).toMatchObject({ confirmStopCurrent: false, loaderVersion: "47.2.0", javaVariant: "java17" }); expect(calls.some(call => call.url.includes("/start"))).toBe(false);
  });
  it("names file jobs as blockers without offering to interrupt them", async () => {
    boundary.operations = opsState({ operations: [op({ game: "minecraft", resources: ["files:minecraft"], title: "Creating a backup" })] }); const calls = requests(); render(<MinecraftProfilePicker open initialProfileId="p2" onOpenChange={vi.fn()} />); await screen.findByText(/Wait for Minecraft/); expect(screen.getByText(/Profile switching does not interrupt these jobs/)).toBeTruthy(); expect(screen.queryByRole("checkbox")).toBeNull(); expect((screen.getByRole("button", { name: "Start selected profile" }) as HTMLButtonElement).disabled).toBe(true); expect(calls.every(call => call.method === "GET")).toBe(true);
  });
  it("invalidates checked disconnection consent when a new running peer appears", async () => {
    boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true, players: { online: 2, max: 10, players: [] } } }) }); const calls = requests(); const view = render(<MinecraftProfilePicker open initialProfileId="p2" onOpenChange={vi.fn()} />); await screen.findByText(/Selected:/); fireEvent.click(screen.getByRole("checkbox")); expect((screen.getByRole("button", { name: "Switch & restart" }) as HTMLButtonElement).disabled).toBe(false);
    boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true, players: { online: 2, max: 10, players: [] } }, zomboid: { status: "online", containerRunning: true } }) }); view.rerender(<MinecraftProfilePicker open initialProfileId="p2" onOpenChange={vi.fn()} />);
    expect((screen.getByRole("checkbox") as HTMLInputElement).checked).toBe(false); expect((screen.getByRole("button", { name: "Switch & restart" }) as HTMLButtonElement).disabled).toBe(true); fireEvent.click(screen.getByRole("checkbox")); fireEvent.click(screen.getByRole("button", { name: "Switch & restart" })); await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(calls.find(call => call.method === "POST")?.body).toMatchObject({ confirmStopPeers: true, confirmedPeers: ["zomboid"] });
  });
  it("keeps a recorded origin and incomplete preparation distinct from current execution", async () => { requests(profilesFixture({ profiles: [profileFixture({ status: "preparing" })] })); render(<MinecraftProfiles />); await screen.findByText(/Check the operation strip to see whether preparation/); expect(screen.queryByText("Preparing")).toBeNull(); expect(screen.getByText("Last played: Not recorded")).toBeTruthy(); expect(screen.getByText("Created from Vanilla · 0 mods")).toBeTruthy(); });
  it("renders sparse world properties without saving defaults the user never edited", async () => {
    const writes: unknown[] = []; vi.stubGlobal("fetch", vi.fn(async (url, init) => { if (init?.method === "PUT") { writes.push(JSON.parse(init.body)); return json({ error: "fixture refusal" }, 400); } if (String(url).endsWith("world-settings")) return json(worldSettingsFixture({ properties: {}, lockedKeys: ["rcon.password"] })); return json({ profile: secondProfile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }); })); render(<MinecraftProfileDetail id="p2" />); await screen.findByRole("textbox", { name: "difficulty" }); expect((screen.getByRole("button", { name: "Save world settings" }) as HTMLButtonElement).disabled).toBe(true); fireEvent.change(screen.getByRole("textbox", { name: "difficulty" }), { target: { value: "hard" } }); fireEvent.click(screen.getByRole("button", { name: "Save world settings" })); await waitFor(() => expect(writes).toEqual([{ updates: { difficulty: "hard" } }])); expect(screen.queryByRole("textbox", { name: "rcon.password" })).toBeNull();
  });
  it("requires metadata revision and canonical readback before clearing its draft", async () => {
    let profile = { ...secondProfile }; const writes: unknown[] = []; vi.stubGlobal("fetch", vi.fn(async (url, init) => { if (init?.method === "PATCH") { const body = JSON.parse(init.body); writes.push(body); profile = { ...profile, name: body.name, description: body.description, revision: 2 }; return json({ profile }); } return String(url).endsWith("world-settings") ? json(worldSettingsFixture()) : json({ profile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }); })); render(<MinecraftProfileDetail id="p2" />); const name = await screen.findByRole("textbox", { name: "Name" }); fireEvent.change(name, { target: { value: "Renamed world" } }); fireEvent.click(screen.getByRole("button", { name: "Save profile details" })); await screen.findByText("Profile details read back and saved."); expect(writes[0]).toMatchObject({ expectedRevision: 1, name: "Renamed world" }); expect((screen.getByRole("button", { name: "Save profile details" }) as HTMLButtonElement).disabled).toBe(true);
  });
  it("freezes a stale metadata draft instead of replacing it or retrying", async () => {
    const calls = requests(profilesFixture(), json({ error: "Profile changed", code: "profile_stale" }, 409)); render(<MinecraftProfileDetail id="p2" />); fireEvent.change(await screen.findByRole("textbox", { name: "Name" }), { target: { value: "My draft" } }); fireEvent.click(screen.getByRole("button", { name: "Save profile details" })); await screen.findByText(/Profile changed/); expect((screen.getByRole("textbox", { name: "Name" }) as HTMLInputElement).value).toBe("My draft"); expect((screen.getByRole("button", { name: "Save profile details" }) as HTMLButtonElement).disabled).toBe(true); expect(calls.filter(call => call.method === "PATCH")).toHaveLength(1);
  });
  it("uploads a screenshot to its profile with expectedRevision and reads back the canonical cover", async () => {
    let profile = { ...secondProfile }; const forms: FormData[] = []; vi.stubGlobal("fetch", vi.fn(async (url, init) => { if (init?.method === "POST") { forms.push(init.body); profile = { ...profile, revision: 2, coverUrl: "/api/minecraft/profiles/p2/cover?v=2" }; return json({ profile }); } return String(url).endsWith("world-settings") ? json(worldSettingsFixture()) : json({ profile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }); })); render(<MinecraftProfileDetail id="p2" />); const input = await screen.findByLabelText("JPEG, PNG or WebP cover"); fireEvent.change(input, { target: { files: [new File([new Uint8Array([137, 80, 78, 71])], "world.png", { type: "image/png" })] } }); fireEvent.click(screen.getByRole("button", { name: "Upload cover" })); await screen.findByText("Cover upload read back."); expect(forms[0].get("expectedRevision")).toBe("1"); expect((forms[0].get("cover") as File).name).toBe("world.png"); expect(screen.getByRole("img", { name: "Cover for Adventure Pack" }).getAttribute("src")).toContain("/api/minecraft/profiles/p2/cover?v=2");
  });
  it("requires a typed canonical profile name and reads back tracked deletion before leaving", async () => {
    let removed = false; const writes: unknown[] = []; vi.stubGlobal("fetch", vi.fn(async (url, init) => { if (init?.method === "DELETE") { writes.push(JSON.parse(init.body)); removed = true; return json({ deleted: true, id: "p2", operationId: "delete-op" }); } if (String(url) === "/api/minecraft/profiles") return json(profilesFixture({ profiles: removed ? [profileFixture()] : [profileFixture(), secondProfile] })); return String(url).endsWith("world-settings") ? json(worldSettingsFixture()) : json({ profile: secondProfile, runtime: profilesFixture().runtime, capabilities: profilesFixture().capabilities }); })); render(<MinecraftProfileDetail id="p2" />); await screen.findByText("Advanced: permanently delete this profile"); fireEvent.click(screen.getByText("Advanced: permanently delete this profile")); fireEvent.click(screen.getByRole("button", { name: "Delete profile" })); const confirm = screen.getByRole("button", { name: "Delete this profile permanently" }) as HTMLButtonElement; expect(confirm.disabled).toBe(true); fireEvent.change(screen.getByRole("textbox", { name: "Profile name confirmation" }), { target: { value: "Adventure Pack " } }); expect(confirm.disabled).toBe(true); fireEvent.change(screen.getByRole("textbox", { name: "Profile name confirmation" }), { target: { value: "Adventure Pack" } }); fireEvent.click(confirm); await screen.findByRole("heading", { name: "Profile removed from the list" }); expect(writes).toEqual([{ expectedRevision: 1, confirm: true }]); expect(toasts.success).not.toHaveBeenCalled();
  });
  it.each(["active", "unknown", "member"])("blocks destructive profile deletion for %s state", async state => {
    const list = profilesFixture(); if (state === "active") list.runtime = { ...list.runtime, selectedProfileId: "p2", appliedProfileId: "p2" }; if (state === "unknown") list.runtime = { ...list.runtime, verified: false, state: "unknown" }; if (state === "member") { boundary.games = gamesState({ can: NO_POWERS }); list.capabilities.manage = false; } const calls = requests(list); render(<MinecraftProfileDetail id="p2" />); await screen.findByText("Advanced: permanently delete this profile"); fireEvent.click(screen.getByText("Advanced: permanently delete this profile")); const button = screen.getByRole("button", { name: "Delete profile" }) as HTMLButtonElement; expect(button.disabled).toBe(true); fireEvent.click(button); expect(calls.every(call => call.method === "GET")).toBe(true);
  });
  it.each([() => <GameControls game="minecraft" />, () => <GameOverview game="minecraft" />])("binds recovery Restart to each newly visible accepted status context", async surface => {
    const writes: Headers[] = []; boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true } }), minecraftContext: "A@1" }); vi.stubGlobal("fetch", vi.fn(async (_url, init) => { if (init?.method === "POST") writes.push(new Headers(init.headers)); return json({ operationId: "restart-op" }); })); const view = render(surface()); fireEvent.click(screen.getByRole("button", { name: "Restart" })); await waitFor(() => expect(writes).toHaveLength(1)); expect(writes[0].get("X-Minecraft-Context")).toBe("A@1"); boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true } }), minecraftContext: "B@2" }); view.rerender(surface()); fireEvent.click(screen.getByRole("button", { name: "Restart" })); await waitFor(() => expect(writes).toHaveLength(2)); expect(writes[1].get("X-Minecraft-Context")).toBe("B@2");
  });
  it("blocks unverified recovery Restart while preserving Power off", async () => { boundary.games = gamesState({ games: worlds({ minecraft: { status: "online", containerRunning: true } }), minecraftContext: null }); const calls = requests(); render(<GameControls game="minecraft" />); expect((screen.getByRole("button", { name: "Restart" }) as HTMLButtonElement).disabled).toBe(true); expect(screen.getByText(/Recovery Restart waits/)).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: /Power off/ })); await waitFor(() => expect(calls.some(call => call.method === "POST")).toBe(true)); expect(calls.find(call => call.method === "POST")?.url).toBe("/api/games/control"); });
});
