// @vitest-environment jsdom
import { afterEach, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { useGames } from "@/lib/use-games";
import { ALL_POWERS, worlds } from "./helpers/dom";
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
const json = (context: string | null, status = 200, detail = "snapshot") => new Response(JSON.stringify({ games: worlds({ minecraft: { detail } }), access: ["minecraft"], can: ALL_POWERS, activeGame: null, running: [], busy: null }), { status, headers: context ? { "X-Minecraft-Context": context } : {} });
function Status() { const state = useGames(0); return <><p>Context: {state.minecraftContext ?? "unverified"}</p><p>Snapshot: {state.games?.minecraft.detail ?? "unread"}</p><button onClick={() => void state.refresh()}>Refresh status</button></>; }
it("captures a context only with an accepted status and rebinds power identity after profile changes", async () => { let reads = 0; vi.stubGlobal("fetch", vi.fn(async () => ++reads === 1 ? json("A@1", 200, "A") : json("B@2", 200, "B"))); render(<Status />); await screen.findByText("Context: A@1"); fireEvent.click(screen.getByRole("button", { name: "Refresh status" })); await screen.findByText("Context: B@2"); expect(screen.getByText("Snapshot: B")).toBeTruthy(); });
it.each([500, 200])("clears action identity after HTTP%s failure or a missing context header", async status => { let reads = 0; vi.stubGlobal("fetch", vi.fn(async () => ++reads === 1 ? json("A@1") : json(null, status))); render(<Status />); await screen.findByText("Context: A@1"); fireEvent.click(screen.getByRole("button", { name: "Refresh status" })); await screen.findByText("Context: unverified"); });
it("cannot attach a delayed older header to a newer accepted status body", async () => { let resolve!: (response: Response) => void; const older = new Promise<Response>(ok => { resolve = ok; }); let reads = 0; vi.stubGlobal("fetch", vi.fn(async () => ++reads === 1 ? json("A@1", 200, "A") : reads === 2 ? older : json("C@3", 200, "C"))); render(<Status />); await screen.findByText("Context: A@1"); fireEvent.click(screen.getByRole("button", { name: "Refresh status" })); fireEvent.click(screen.getByRole("button", { name: "Refresh status" })); await screen.findByText("Context: C@3"); await act(async () => resolve(json("B@2", 200, "B"))); expect(screen.getByText("Context: C@3")).toBeTruthy(); expect(screen.getByText("Snapshot: C")).toBeTruthy(); });
